## 1. Importing libraries

In [2]:
import heapq, numpy as np
from typing import Iterable

## 2. Exploration

In [3]:
heapq.heappush?

Signature: heapq.heappush(heap, item, /)
Docstring: Push item onto heap, maintaining the heap invariant.
Type:      builtin_function_or_method

In [4]:
heapq.heappop?

Signature: heapq.heappop(heap, /)
Docstring: Pop the smallest item off the heap, maintaining the heap invariant.
Type:      builtin_function_or_method

In [11]:
heapq.heapify?

Signature: heapq.heapify(heap, /)
Docstring: Transform list into a heap, in-place, in O(len(heap)) time.
Type:      builtin_function_or_method

In [26]:
def heapsort(arr: Iterable):
    h = []
    for i in arr:
        heapq.heappush(h,i)
    return h, [heapq.heappop(h) for _ in range(int(len(h)/2))]

N = 10
input = np.random.random(N)
h, sorted_series = heapsort(input)

In [27]:
h

[0.722845691464518,
 0.7972719044585193,
 0.799781102165968,
 0.8817270546584974,
 0.8117553195039844]

In [28]:
sorted_series

[0.18459728848429124,
 0.3568005025786366,
 0.4152864600494256,
 0.6085906663932582,
 0.697160750529376]

In [29]:
input

array([0.7997811 , 0.60859067, 0.3568005 , 0.18459729, 0.81175532,
       0.88172705, 0.69716075, 0.7972719 , 0.72284569, 0.41528646])

In [35]:
input_list = input.tolist()
heapq.heapify(input_list)

In [36]:
input_list

[0.18459728848429124,
 0.4152864600494256,
 0.3568005025786366,
 0.6085906663932582,
 0.799781102165968,
 0.8817270546584974,
 0.697160750529376,
 0.7972719044585193,
 0.722845691464518,
 0.8117553195039844]

In [37]:
input_list[4]

0.799781102165968

### Kth smallest element

In [52]:
def find_kth_smallest(arr: Iterable, k: int):
    
    h = []
    if not isinstance(arr, list):
        arr = arr.tolist()
    L = len(arr)
    for i in range(L):
        heapq.heappush(h, -arr[i])
        if i > k:
            heapq.heappop(h) # Pushes the smallest element out of the heap
    return -h[0]

N = 10
input = np.random.random(N)
h = find_kth_smallest(arr=input, k=3)
print(h)  

# Validation
input.sort()
input

0.2980607668503462


array([0.12040617, 0.14384801, 0.22948445, 0.29806077, 0.4230669 ,
       0.55311934, 0.63762656, 0.78447164, 0.83278236, 0.95292076])

### Kth largest element

In [53]:
def find_kth_largest(arr: Iterable, k: int):
    
    h = []
    if not isinstance(arr, list):
        arr = arr.tolist()
    L = len(arr)
    for i in range(L):
        heapq.heappush(h, arr[i])
        if i > k:
            heapq.heappop(h) # Pushes the smallest element out of the heap
    return h[0]

N = 10
input = np.random.random(N)
h = find_kth_largest(arr=input, k=3)
print(h)  

# Validation
input.sort()
input

0.47807469022185745


array([0.0252613 , 0.0708132 , 0.23115199, 0.24043398, 0.32648946,
       0.44744703, 0.47807469, 0.68059494, 0.80353045, 0.93819994])